import { useEffect, useState } from "react";
import { Copy, ShieldCheck, Users, Zap } from "lucide-react";
import { SERVER_URL } from "../config/urls";

export function CopyTradingCenter(){
 const [s,setS]=useState({enabled:false,allocationPct:10,maxPositionUsdt:100,maxDailyLossUsdt:20,maxConcurrentCopies:3,copyNewTradesOnly:true});const [saving,setSaving]=useState(false);const [msg,setMsg]=useState("");
 useEffect(()=>{const t=localStorage.getItem("pcb_jwt");fetch(`${SERVER_URL}/api/copy-trading/settings`,{headers:t?{Authorization:`Bearer ${t}`}:{}}).then(r=>r.json()).then(d=>d.settings&&setS(d.settings)).catch(()=>{});},[]);
 const set=(k:string,v:unknown)=>setS(x=>({...x,[k]:v}));
 async function save(){setSaving(true);try{const t=localStorage.getItem("pcb_jwt");const r=await fetch(`${SERVER_URL}/api/copy-trading/settings`,{method:"PUT",headers:{"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})},body:JSON.stringify(s)});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.error??"Save failed");setS(d.settings);setMsg("Copy trading preferences saved.");}catch(e){setMsg(e instanceof Error?e.message:"Save failed");}finally{setSaving(false)}}
 return <div className="space-y-6"><div className="rounded-3xl border border-amber-500/20 bg-gradient-to-br from-amber-950/25 to-[#0b0f18] p-7"><div className="flex items-center gap-3 text-amber-300 text-xs font-black uppercase tracking-[.25em]"><Copy size={18}/> Phase 15 Copy Trading</div><h1 className="mt-2 text-3xl font-black text-white">Copy Trading Center</h1><p className="mt-2 max-w-3xl text-slate-400">Configure your future copy-trading risk profile now. The platform is prepared for trader discovery and follower limits; cross-user live replication remains locked until multi-account permissions are enabled.</p></div>
 <div className="grid xl:grid-cols-3 gap-5"><div className="xl:col-span-2 rounded-3xl border border-white/10 bg-[#0d1119] p-6"><div className="grid md:grid-cols-2 gap-5"><label className="flex items-center justify-between rounded-2xl border border-white/10 p-4"><span><b className="block text-white">Enable copy trading</b><small className="text-slate-500">Allow this account to become a follower</small></span><input type="checkbox" checked={s.enabled} onChange={e=>set("enabled",e.target.checked)} className="h-5 w-5"/></label><label className="flex items-center justify-between rounded-2xl border border-white/10 p-4"><span><b className="block text-white">Copy new trades only</b><small className="text-slate-500">Do not backfill historical positions</small></span><input type="checkbox" checked={s.copyNewTradesOnly} onChange={e=>set("copyNewTradesOnly",e.target.checked)} className="h-5 w-5"/></label>{([["allocationPct","Allocation per copied trade %"],["maxPositionUsdt","Maximum copied position USDT"],["maxDailyLossUsdt","Maximum daily copy loss USDT"],["maxConcurrentCopies","Maximum concurrent copies"]] as const).map(([k,l])=><label key={k}><span className="text-xs font-bold text-slate-500">{l}</span><input type="number" value={s[k]} onChange={e=>set(k,Number(e.target.value))} className="mt-2 w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3 text-white font-black outline-none"/></label>)}</div><button onClick={()=>void save()} disabled={saving} className="mt-6 rounded-2xl bg-amber-500 px-6 py-3 font-black text-black disabled:opacity-50">{saving?"Saving…":"Save Copy Settings"}</button>{msg&&<p className="mt-3 text-sm text-cyan-300">{msg}</p>}</div><div className="space-y-4"><div className="rounded-3xl border border-white/10 bg-[#0d1119] p-6"><Users className="text-cyan-400"/><h3 className="mt-3 text-lg font-black text-white">Trader discovery</h3><p className="mt-2 text-sm text-slate-500">The API contract is ready for public trader profiles, performance and follower rankings.</p></div><div className="rounded-3xl border border-emerald-500/20 bg-emerald-500/5 p-6"><ShieldCheck className="text-emerald-400"/><h3 className="mt-3 font-black text-emerald-300">Safety first</h3><p className="mt-2 text-sm text-slate-400">Copy limits are stored independently so a follower can cap allocation, daily losses and concurrent positions.</p></div><div className="rounded-3xl border border-violet-500/20 bg-violet-500/5 p-6"><Zap className="text-violet-300"/><h3 className="mt-3 font-black text-violet-200">Next infrastructure step</h3><p className="mt-2 text-sm text-slate-400">Live cross-user replication requires isolated account ownership and permission checks before real trades can be mirrored.</p></div></div></div></div>
}
