import { useEffect, useState } from "react";
import { BrainCircuit, Save, SlidersHorizontal } from "lucide-react";
import { SERVER_URL } from "../config/urls";

type Profile = { id:string; label:string; enabled:boolean; timeframe:string; minConfidence:number; tpPct:number; slPct:number; maxTradesPerDay:number; cooldownMinutes:number };

export function StrategyLab(){
 const [profiles,setProfiles]=useState<Profile[]>([]); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState("");
 useEffect(()=>{const t=localStorage.getItem("pcb_jwt"); fetch(`${SERVER_URL}/api/strategy-profiles`,{headers:t?{Authorization:`Bearer ${t}`}:{}}).then(r=>r.json()).then(d=>setProfiles(d.profiles??[])).catch(()=>{});},[]);
 const update=(id:string,k:keyof Profile,v:unknown)=>setProfiles(p=>p.map(x=>x.id===id?{...x,[k]:v}:x));
 async function save(){setSaving(true);setMsg("");try{const t=localStorage.getItem("pcb_jwt");const r=await fetch(`${SERVER_URL}/api/strategy-profiles`,{method:"PUT",headers:{"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})},body:JSON.stringify({profiles})});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.error??"Save failed");setProfiles(d.profiles);setMsg("Strategy profiles saved.");}catch(e){setMsg(e instanceof Error?e.message:"Save failed");}finally{setSaving(false)}}
 return <div className="space-y-6"><div className="rounded-3xl border border-violet-500/20 bg-gradient-to-br from-violet-950/30 to-[#0b0f18] p-7"><div className="flex items-center gap-3 text-violet-300 text-xs font-black uppercase tracking-[.25em]"><BrainCircuit size={18}/> Phase 15 Strategy Lab</div><h1 className="mt-2 text-3xl font-black text-white">Strategy Profiles</h1><p className="mt-2 text-slate-400 max-w-3xl">Centralize the operational profile for each strategy: timeframe, confidence threshold, target, stop, trade frequency and cooldown. These profiles are persisted independently from the dashboard.</p></div>
 <div className="grid xl:grid-cols-3 gap-5">{profiles.map(p=><div key={p.id} className="rounded-3xl border border-white/10 bg-[#0d1119] p-5 shadow-xl"><div className="flex justify-between items-start"><div><h2 className="font-black text-white text-lg">{p.label}</h2><p className="text-xs text-slate-500 mt-1">{p.id}</p></div><button onClick={()=>update(p.id,"enabled",!p.enabled)} className={`rounded-full px-3 py-1 text-xs font-black ${p.enabled?"bg-emerald-500/15 text-emerald-300":"bg-slate-800 text-slate-500"}`}>{p.enabled?"ENABLED":"DISABLED"}</button></div><div className="mt-5 space-y-4">{([["timeframe","Timeframe",p.timeframe],["minConfidence","Min confidence %",p.minConfidence],["tpPct","TP %",p.tpPct],["slPct","SL %",p.slPct],["maxTradesPerDay","Max trades/day",p.maxTradesPerDay],["cooldownMinutes","Cooldown minutes",p.cooldownMinutes]] as const).map(([k,label,val])=><label key={k} className="block"><span className="text-[11px] font-bold uppercase tracking-wider text-slate-500">{label}</span><input value={val} type={k==="timeframe"?"text":"number"} onChange={e=>update(p.id,k,k==="timeframe"?e.target.value:Number(e.target.value))} className="mt-1.5 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm font-bold text-white outline-none focus:border-violet-400/40"/></label>)}</div></div>)}</div>
 <div className="flex items-center justify-between rounded-2xl border border-white/10 bg-[#0d1119] p-4"><div className="flex items-center gap-2 text-sm text-slate-400"><SlidersHorizontal size={17}/> Profiles are stored server-side and ready for strategy-specific execution authority wiring.</div><button onClick={()=>void save()} disabled={saving} className="flex items-center gap-2 rounded-xl bg-violet-500 px-5 py-3 font-black text-white disabled:opacity-50"><Save size={17}/>{saving?"Saving…":"Save Profiles"}</button></div>{msg&&<p className="text-sm text-cyan-300">{msg}</p>}</div>
}
