/**
 * tradeReviewEngine.ts — Phase 9.2 AI Trade Review
 *
 * After every trade, generates a structured review explaining:
 *   • why the trade opened (entry rationale)
 *   • why it closed (exit rationale)
 *   • strengths of the setup
 *   • weaknesses / risks taken
 *   • lessons learned
 *
 * Uses rule-based analysis to generate human-readable insights without
 * external AI API dependency. Reviews are stored in an in-memory ring buffer.
 */

import { logger } from "./logger";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface TradeContext {
  tradeId:      string;
  symbol:       string;
  strategyId:   string;
  side:         "buy" | "sell";
  entryPrice:   number;
  exitPrice:    number;
  pnlUsd:       number;
  pnlPct:       number;
  holdMins:     number;
  exitReason:   "tp" | "sl" | "signal" | "end" | "manual";
  regime:       string;
  rsi?:         number;
  ema50?:       number;
  ema200?:      number;
  volRatio?:    number;
  slippagePct?: number;
}

export interface TradeReview {
  tradeId:       string;
  symbol:        string;
  strategyId:    string;
  outcome:       "win" | "loss" | "breakeven";
  pnlUsd:        number;
  pnlPct:        number;
  entryRationale: string;
  exitRationale:  string;
  strengths:      string[];
  weaknesses:     string[];
  lessons:        string[];
  rating:         number;   // 0-10 trade quality score
  createdAt:      string;
}

// ─── Rule-based analysis helpers ─────────────────────────────────────────────

function describeEntry(ctx: TradeContext): string {
  const parts: string[] = [];
  const strat = ctx.strategyId.replace("-", " ").toUpperCase();
  parts.push(`${strat} strategy triggered a ${ctx.side.toUpperCase()} signal on ${ctx.symbol}.`);

  if (ctx.rsi != null) {
    if (ctx.side === "buy"  && ctx.rsi < 40) parts.push(`RSI was oversold at ${ctx.rsi.toFixed(1)}, supporting a long entry.`);
    if (ctx.side === "buy"  && ctx.rsi > 60) parts.push(`RSI was elevated at ${ctx.rsi.toFixed(1)}; entry was momentum-based, not mean-reversion.`);
    if (ctx.side === "sell" && ctx.rsi > 60) parts.push(`RSI was overbought at ${ctx.rsi.toFixed(1)}, supporting a short entry.`);
  }
  if (ctx.ema50 != null && ctx.ema200 != null) {
    const bullish = ctx.ema50 > ctx.ema200;
    parts.push(`Price was in a ${bullish ? "bullish (EMA50 > EMA200)" : "bearish (EMA50 < EMA200)"} trend at entry.`);
  }
  if (ctx.regime) parts.push(`Market regime at entry: ${ctx.regime.replace("_", " ")}.`);
  if (ctx.volRatio != null) {
    if (ctx.volRatio > 1.5) parts.push(`Volatility was elevated (${ctx.volRatio.toFixed(2)}× average) — higher risk environment.`);
    else if (ctx.volRatio < 0.7) parts.push(`Low volatility (${ctx.volRatio.toFixed(2)}× average) — calmer conditions at entry.`);
  }
  return parts.join(" ");
}

function describeExit(ctx: TradeContext): string {
  const reasonMap: Record<string, string> = {
    tp:     `Trade hit the take-profit target at $${ctx.exitPrice.toFixed(4)}.`,
    sl:     `Stop-loss was triggered at $${ctx.exitPrice.toFixed(4)}, limiting the loss.`,
    signal: `Exit signal generated by strategy — position closed proactively at $${ctx.exitPrice.toFixed(4)}.`,
    end:    `Trade closed at end-of-session with no explicit signal, at $${ctx.exitPrice.toFixed(4)}.`,
    manual: `Trade was manually closed at $${ctx.exitPrice.toFixed(4)}.`,
  };
  const base = reasonMap[ctx.exitReason] ?? `Trade closed at $${ctx.exitPrice.toFixed(4)}.`;
  const hold = ctx.holdMins < 60
    ? `Held for ${ctx.holdMins} minutes.`
    : `Held for ${(ctx.holdMins / 60).toFixed(1)} hours.`;
  const pnl  = ctx.pnlUsd >= 0
    ? `Net gain: $${ctx.pnlUsd.toFixed(2)} (+${ctx.pnlPct.toFixed(2)}%).`
    : `Net loss: $${Math.abs(ctx.pnlUsd).toFixed(2)} (${ctx.pnlPct.toFixed(2)}%).`;
  return `${base} ${hold} ${pnl}`;
}

function analyseStrengths(ctx: TradeContext): string[] {
  const s: string[] = [];
  if (ctx.exitReason === "tp") s.push("Clean take-profit exit — trade reached its target without being stopped out.");
  if (ctx.pnlUsd > 0 && ctx.holdMins < 120) s.push("Quick profitable trade — efficient capital deployment.");
  if (ctx.rsi != null && ctx.side === "buy" && ctx.rsi < 35) s.push("Entry at oversold RSI levels — good mean-reversion timing.");
  if (ctx.rsi != null && ctx.side === "sell" && ctx.rsi > 65) s.push("Entry at overbought RSI levels — good mean-reversion timing.");
  if (ctx.ema50 != null && ctx.ema200 != null) {
    if (ctx.side === "buy" && ctx.ema50 > ctx.ema200) s.push("Trade was aligned with the prevailing uptrend.");
    if (ctx.side === "sell" && ctx.ema50 < ctx.ema200) s.push("Trade was aligned with the prevailing downtrend.");
  }
  if (ctx.slippagePct != null && Math.abs(ctx.slippagePct) < 0.1) s.push("Excellent fill quality — minimal slippage.");
  if (ctx.pnlUsd > 0 && ctx.pnlPct > 2) s.push("Above-average return — setup had good risk/reward.");
  return s.length > 0 ? s : ["Trade executed per strategy rules."];
}

function analyseWeaknesses(ctx: TradeContext): string[] {
  const w: string[] = [];
  if (ctx.exitReason === "sl") w.push("Stop-loss hit — setup did not play out as expected.");
  if (ctx.pnlUsd < 0 && Math.abs(ctx.pnlPct) > 2) w.push("Larger-than-ideal loss — consider tightening stop or reducing position size.");
  if (ctx.holdMins > 480 && ctx.pnlUsd <= 0) w.push("Long hold time with negative outcome — consider time-based exit rules.");
  if (ctx.volRatio != null && ctx.volRatio > 1.5 && ctx.pnlUsd < 0) w.push("Entered in high-volatility regime — these conditions increase stop-out probability.");
  if (ctx.rsi != null && ctx.side === "buy" && ctx.rsi > 70 && ctx.pnlUsd < 0) w.push("Buy entry with overbought RSI led to a loss — avoid chasing momentum at extremes.");
  if (ctx.slippagePct != null && Math.abs(ctx.slippagePct) > 0.3) w.push(`Slippage of ${Math.abs(ctx.slippagePct).toFixed(2)}% reduced profitability — consider limit orders.`);
  if (ctx.exitReason === "end" && ctx.pnlUsd < 0) w.push("No exit signal generated before session end — strategy lacked a clear exit condition.");
  return w.length > 0 ? w : ["No significant weaknesses identified."];
}

function deriveLessons(ctx: TradeContext): string[] {
  const l: string[] = [];
  if (ctx.exitReason === "sl") l.push("Always respect stop-losses. The market can move further than expected.");
  if (ctx.pnlUsd > 0) l.push("When the setup aligns with regime and indicators, let the trade run to target.");
  if (ctx.volRatio != null && ctx.volRatio > 1.5) l.push("In volatile regimes, reduce position size or wait for confirmation before entering.");
  if (ctx.holdMins < 10 && ctx.pnlUsd < 0) l.push("Very quick losses can indicate noise — consider entry confirmation filters.");
  if (ctx.exitReason === "tp" && ctx.pnlPct > 3) l.push("High-conviction setups with strong regime alignment can yield strong returns.");
  if (ctx.regime === "ranging" && ctx.strategyId === "swing") l.push("Swing strategy underperforms in ranging markets — prefer scalping/DCA in low-trend conditions.");
  return l.length > 0 ? l : ["Continue following the system rules and tracking outcomes."];
}

function rateQuality(ctx: TradeContext): number {
  let score = 5;
  if (ctx.pnlUsd > 0) score += 2;
  if (ctx.exitReason === "tp") score += 1;
  if (ctx.exitReason === "sl") score -= 1;
  if (ctx.slippagePct != null && Math.abs(ctx.slippagePct) < 0.1) score += 0.5;
  if (ctx.slippagePct != null && Math.abs(ctx.slippagePct) > 0.5) score -= 0.5;
  if (ctx.rsi != null && ctx.side === "buy" && ctx.rsi < 40)  score += 0.5;
  if (ctx.rsi != null && ctx.side === "sell" && ctx.rsi > 60) score += 0.5;
  if (ctx.ema50 != null && ctx.ema200 != null) {
    if ((ctx.side === "buy" && ctx.ema50 > ctx.ema200) || (ctx.side === "sell" && ctx.ema50 < ctx.ema200)) score += 0.5;
  }
  return Math.max(0, Math.min(10, Math.round(score * 10) / 10));
}

// ─── Service class ────────────────────────────────────────────────────────────

class TradeReviewEngine {
  private reviews = new Map<string, TradeReview>();
  private readonly maxReviews = 200;

  /** Generate review for a completed trade */
  generateReview(ctx: TradeContext): TradeReview {
    const outcome: TradeReview["outcome"] =
      ctx.pnlUsd > 0.01 ? "win" : ctx.pnlUsd < -0.01 ? "loss" : "breakeven";

    const review: TradeReview = {
      tradeId:        ctx.tradeId,
      symbol:         ctx.symbol,
      strategyId:     ctx.strategyId,
      outcome,
      pnlUsd:         Math.round(ctx.pnlUsd * 100) / 100,
      pnlPct:         Math.round(ctx.pnlPct * 100) / 100,
      entryRationale: describeEntry(ctx),
      exitRationale:  describeExit(ctx),
      strengths:      analyseStrengths(ctx),
      weaknesses:     analyseWeaknesses(ctx),
      lessons:        deriveLessons(ctx),
      rating:         rateQuality(ctx),
      createdAt:      new Date().toISOString(),
    };

    this.reviews.set(ctx.tradeId, review);
    if (this.reviews.size > this.maxReviews) {
      const oldest = [...this.reviews.keys()][0];
      if (oldest) this.reviews.delete(oldest);
    }

    logger.info({ tradeId: ctx.tradeId, outcome, rating: review.rating }, "TradeReview: generated");
    return review;
  }

  getReview(tradeId: string): TradeReview | null { return this.reviews.get(tradeId) ?? null; }

  getRecent(limit = 20): TradeReview[] {
    return Array.from(this.reviews.values())
      .sort((a, b) => b.createdAt.localeCompare(a.createdAt))
      .slice(0, limit);
  }

  getStats(): { total: number; wins: number; losses: number; avgRating: number } {
    const all = Array.from(this.reviews.values());
    return {
      total:     all.length,
      wins:      all.filter((r) => r.outcome === "win").length,
      losses:    all.filter((r) => r.outcome === "loss").length,
      avgRating: all.length > 0 ? Math.round(all.reduce((s, r) => s + r.rating, 0) / all.length * 10) / 10 : 0,
    };
  }
}

export const tradeReviewEngine = new TradeReviewEngine();
